version: "3.5"

services:

  db-services-it:
    container_name: db-services-it
    image: "postgres:12"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    ports:
      - "5432:5432"
#    networks:
#      - gprckafka
#
#networks:
#  gprckafka:
#    name: gprckafka
#    driver: bridge
